### ISSUE TITLE
Import Errors in DevOpsTools.sol

### ISSUE THREAD

**Issue by allwin199** [ChainAccelOrg/foundry-devops#14]
https://github.com/Cyfrin/foundry-devops/blob/53e22e4d4f389641a076fabe3b2672cd4db21251/src/DevOpsTools.sol#L5-L8

While using the above lines of code. I am getting an error file not found.

I have replaced it with relative paths and it worked.

```solidity
import {Vm} from "../../forge-std/src/Vm.sol";
import {stdJson} from "../../forge-std/src/StdJson.sol";
import {StdCheatsSafe} from "../../forge-std/src/StdCheats.sol";
import {console} from "../../forge-std/src/console.sol";
```

Let me know If I am missing something.

**Comment by PatrickAlphaC** [comment]
hmm... could you make a PR with this change per chance?

**Comment by allwin199** [comment]
Sure!

**Comment by allwin199** [comment]
I think the error is on my side not in the library.

**Comment by dada22222222** [comment]
What was the issue?
