### ISSUE TITLE
Add Details to update forge-std library

### ISSUE THREAD

**Issue by allwin199** [ChainAccelOrg/foundry-devops#15]
https://github.com/Cyfrin/foundry-devops/pull/10#issuecomment-1817904497

As mentioned in the above comment cheat codes like `Vm.DirEntry[]`  and  `vm.keyExists` are available only in the versions above 6.0.

Another issue I noticed is If we don't update forge-std lib. During contract verification, only the `DevOpsTools` contract is verified.

Adding commands mentioned in the original PR will help.

```sh
forge rm forge-std -f
```

```sh
forge install foundry-rs/forge-std@v1.7.0
```

I am willing to make these changes.

**Comment by PatrickAlphaC** [comment]
Sounds good to me :)
