### ISSUE TITLE
avoid deployment of library contract

### ISSUE THREAD

**Issue by jjoshm** [ChainAccelOrg/foundry-devops#18]
### on the 0.1.0 tag:
if you call the get_most_recent_deployment function outside the broadcast and then deploy a contract in the same script it will deploy an additional DevOpsTools contract as a library.

----

### on the master branch:
if you provide 3 arguments to the get_most_recent_deployment outside the broadcast and then deploy a contract in the same script it will deploy an additional DevOpsTools contract as a library.

----

PR: https://github.com/Cyfrin/foundry-devops/pull/19

**Comment by PatrickAlphaC** [comment]
fixed in 61f46bd03a21efa92d8f36d81664f3ef51dec307
