### ISSUE TITLE
`vm.keyExists` has been deprecated 

### ISSUE THREAD

**Issue by inallhonesty** [ChainAccelOrg/foundry-devops#20]
I'm currently writing the `Lesson 19: Create integration` tutorial from `Section 1: Fund Me`. In there we use the `DevOpsTools.get_most_recent_deployment` function to get the most recently deployed address of `FundMe`. The project doesn't build for the following reason:

```
[⠰] Compiling...
[⠒] Compiling 29 files with Solc 0.8.19
[⠢] Solc 0.8.19 finished in 578.90ms
Error: 
Compiler run failed:
Error (9582): Member "keyExists" not found or not visible after argument-dependent lookup in contract Vm.
   --> lib/foundry-devops/src/DevOpsTools.sol:119:13:
    |
119 |         if (vm.keyExists(json, "$.transactions[0].rpc")) {
    |         
```

Searching for `keyExists` in the [Foundry Handbook](https://book.getfoundry.sh/cheatcodes/key-exists?highlight=keyExistsJson#status) we find out that this cheatcode has been deprecated in favor of `keyExistsJson`. 

I tried replacing the `keyExists` in `lib/foundry-devops/src/DevOpsTools.sol:119` with `keyExistsJson` but it errored out due to:

```
[⠰] Compiling...
[⠊] Compiling 29 files with Solc 0.8.19
[⠒] Solc 0.8.19 finished in 559.33ms
Error: 
Compiler run failed:
Error (9582): Member "keyExistsJson" not found or not visible after argument-dependent lookup in contract Vm.
   --> lib/foundry-devops/src/DevOpsTools.sol:119:13:
    |
119 |         if (vm.keyExistsJson(json, "$.transactions[0].rpc")) {
    |             ^^^^^^^^^^^^^^^^
```

I searched for this function in the `Vm.sol` of the `forge-std` that `foundry-devops` uses and it's not there because the `forge-std` is too old.

Please update the `forge-std` libray and replace `vm.keyExists` with `vm.keyExistsJson` at `foundry-devops/src/DevOpsTools.sol:119`

**Comment by PatrickAlphaC** [comment]
fixed in main
