### ISSUE TITLE
Add foundry-devops to Soldeer

### ISSUE THREAD

**Issue by 0xharold** [ChainAccelOrg/foundry-devops#26]
I would like to kindly ask you if you could add this amazing tool to the Soldeer (see [step-by-step](https://github.com/mario-eth/soldeer?tab=readme-ov-file#how-to-push-a-new-dependency-to-the-repository)). 

Would do it myself but not sure if it is desired. :)

Thanks in advance.

**Comment by PatrickAlphaC** [comment]
It's up!

https://soldeer.xyz/project/foundry-devops
