### ISSUE TITLE
Contract interaction issues

### ISSUE THREAD

**Issue by qt-wu** [ChainAccelOrg/foundry-devops#30]
When I interact with the contract, this problem occurs. What is the reason?
![image](https://github.com/user-attachments/assets/34fbc1f3-c882-45b3-83fd-dd682feefca1)

**Comment by Equious** [comment]
Typically this is an issue reading things from the broadcast folder. You can usually run `forge clean` and `forge build` to resolve.

If you have further issues, please open a discussion thread on the course repo, or join us in [Discord](https://discord.gg/SJrxnU96)
