### ISSUE TITLE
[Improvement] use `fs_permission` instead of `ffi`

### ISSUE THREAD

**Issue by foufrix** [ChainAccelOrg/foundry-devops#8]
I just went through your course, and you propose to change the code to work with Foundry `fs_permission` instead of allowing `ffi`

Example of where it can be useful in [Cyfrin course lesson](https://youtu.be/sas02qSFZ74?t=33530) 

[`fs_permission` docs](https://book.getfoundry.sh/cheatcodes/fs?highlight=fs_permission)

[`ffi` docs](https://book.getfoundry.sh/cheatcodes/ffi)

**Comment by PatrickAlphaC** [comment]
Yes, this would be great

**Comment by PatrickAlphaC** [comment]
https://github.com/Cyfrin/foundry-devops/pull/10
